### ISSUE TITLE
support for ClojureScript

### ISSUE THREAD

**Issue by skprasadu** [floybix/cljbox2d#1]
Are there any plans for ClojureScript support. We have been using cljbox2d in our project.

I presume, there is already javascript of Box2d, it might be a good idea.

Please let me know.

Thanks
Krishna

**Comment by floybix** [comment]
I don't have specific plans for clojurescript, but agree it would be nice. I see there is a good js port at https://github.com/google/liquidfun/blob/master/liquidfun/Box2D/lfjs/liquidfun.js which also seems like it works with google closure compiler... but I have never tried linking cljsbuild to an external js library before. If you feel like having a go?

**Comment by skprasadu** [comment]
Hello Felix,

Thanks for getting back to me. We have an internal project where we need to
use/ build capacities around complex physic engine. Your framework is
perfect for this. But we also need Html Canvas support and quil framework
on ClojureScript is ideal.

I am new to Clojure and looking around web I found
https://github.com/annejohnson/cljs-raphael, where they have demoed how to
configure Raphael with ClojureScript..

I am open to writing cljbox for ClojureScript.. can you guide me.

Thanks for any help you can offer.

Krishna Prasad
Phone#: +14087969283

Linkedin: http://www.linkedin.com/in/krishnaprasad1

**Comment by floybix** [comment]
Better late than never right? ha ha
